/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.autonoma.friendsbirthday.gui;

import co.edu.autonoma.friendsbirthday.FriendsBirthday;
import co.edu.autonoma.friendsbirthday.elements.Friend;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author educacion
 */
public class MainFrame extends javax.swing.JFrame {

    private FriendsBirthday friends = null;
    
    /**
     * Creates new form MainFrame
     * @param friends
     */
    public MainFrame(FriendsBirthday friends) {
        initComponents();
        
        this.friends = friends;
        
        this.bRefreshActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTable = new javax.swing.JTable();
        bNew = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        bView = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        jLabel1.setText("Friends Birthday");

        tTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tTable);

        bNew.setText("New");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bView.setText("View");
        bView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bViewActionPerformed(evt);
            }
        });

        bAbout.setText("About");
        bAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addComponent(bRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNew)
                    .addComponent(bEdit)
                    .addComponent(bDelete)
                    .addComponent(bView)
                    .addComponent(bAbout)
                    .addComponent(bExit)
                    .addComponent(bRefresh))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        friends.close();
    }//GEN-LAST:event_bExitActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        String message = """
                         *** Birthday Friends ***
                         
                         Desarrollado por Jorge I. Meza
                         jimezam@autonoma.edu.co
                         
                         Semillero de Programación en Ingeniería de Software
                         Departamento de Ciencias Computacionales
                         Universidad Autónoma de Manizales
                         
                         2022
                         """;
        
        JOptionPane.showMessageDialog(this, message, "About this", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bAboutActionPerformed

    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        FriendProperties dialog = new FriendProperties(this, true, FriendProperties.TYPE_CREATE);
        dialog.setVisible(true);
        
        if(dialog.isStatus())
        {
            Friend friend = new Friend(dialog.getEmail(), 
                                       dialog.getName(), 
                                       dialog.getBirthday());
            
            if(friends.addFriend(friend))
                this.bRefreshActionPerformed(null);
        }
    }//GEN-LAST:event_bNewActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        ResultSet result = friends.getAllFriends();
        
        if(result != null)
        {
            try {
                tTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                tTable.setModel(updateModel(result));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error refreshing records", 
                                              "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bRefreshActionPerformed

    public DefaultTableModel updateModel(ResultSet resultset) throws SQLException
    {
        ResultSetMetaData metaData = resultset.getMetaData();

        Vector<String> columnNames = new Vector<>();

        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<>();
        while (resultset.next()) {
            Vector<Object> vector = new Vector<Object>();
            
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(resultset.getObject(columnIndex));
            }
            data.add(vector);
        }
        
        return new DefaultTableModel(data, columnNames);
    }
        
    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        int row = tTable.getSelectedRow();
        
        if(row < 0)
        {
            JOptionPane.showMessageDialog(this, "A row must be selected to delete", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        long id = 0;

        if(tTable.getValueAt(row, 0) != null)
            id = (Long) tTable.getValueAt(row, 0);
        else
        {
            JOptionPane.showMessageDialog(this, "A valid row must be selected to delete", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(friends.deleteFriend(id))
            this.bRefreshActionPerformed(null);
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bViewActionPerformed
        int row = tTable.getSelectedRow();
        
        if(row < 0)
        {
            JOptionPane.showMessageDialog(this, "A row must be selected to view", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        long id = 0;

        if(tTable.getValueAt(row, 0) != null)
            id = (Long) tTable.getValueAt(row, 0);
        else
        {
            JOptionPane.showMessageDialog(this, "A valid row must be selected to view", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Friend friend = friends.getFriend(id);

        if(friend == null)
        {
            JOptionPane.showMessageDialog(this, "The record was not loaded: " + id, 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        FriendProperties dialog = new FriendProperties(this, true, FriendProperties.TYPE_VIEW);
        dialog.setData(friend);
        dialog.setVisible(true);
    }//GEN-LAST:event_bViewActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        int row = tTable.getSelectedRow();
        
        if(row < 0)
        {
            JOptionPane.showMessageDialog(this, "A row must be selected to edit", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        long id = 0;

        if(tTable.getValueAt(row, 0) != null)
            id = (Long) tTable.getValueAt(row, 0);
        else
        {
            JOptionPane.showMessageDialog(this, "A valid row must be selected to edit", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Friend friend = friends.getFriend(id);

        if(friend == null)
        {
            JOptionPane.showMessageDialog(this, "The record was not loaded: " + id, 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        FriendProperties dialog = new FriendProperties(this, true, FriendProperties.TYPE_EDIT);
        dialog.setData(friend);
        dialog.setVisible(true);
        
        if(!dialog.isStatus())
            return;
        
        friend.setName(dialog.getName());
        friend.setEmail(dialog.getEmail());
        friend.setBirthday(dialog.getBirthday());
        
        if(friends.updateFriend(friend))
            this.bRefreshActionPerformed(null);
    }//GEN-LAST:event_bEditActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bNew;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tTable;
    // End of variables declaration//GEN-END:variables
}
